### ISSUE TITLE
Is possible that multiple authors use this theme?

### ISSUE THREAD

**Issue by Skabit** [gethugothemes/persian-hugo#10]
I created three authors for this theme but I look some inconsistencies. In the home page when it has only two articles, they looks really bad. Images disappears. In this example I have three authors, but only two have a author page (in this path: `/content/author/joe-doe.md`). I don't understand why persian theme parses bad when I have multiple authors setting. Please any hint for fixing this?

![error1](https://user-images.githubusercontent.com/71466998/104856923-11063b00-590d-11eb-9998-f09a5459d057.png)

**Comment by somratpro** [comment]
Hello @Skabit,

This theme does not support multiple authors for a single post. Please contact mehedi@themefisher.com (paid). for theme customization. thank you

**Comment by Skabit** [comment]
I see. Anyway, thanks for all.
