### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by totoroot** [gethugothemes/persian-hugo#11]
Hey there,

I thought about using this theme for an NGO website of a friend of mine and like the overall look and feel.

However, even though the [theme description](https://themes.gohugo.io/persian-hugo/) reads 'It is very responsive and perfectly fits on any size screen device.' I tested the [demo](https://themes.gohugo.io/theme/persian-hugo/) in Firefox responsive mode and was not able to confirm this statement.
For devices with displays with less than about 420px in width like for example the iPhone 5/SE or the Microsoft Lumia 950 the elements in the post overview are either cropped or squashed.

Here are examples of what I'm talking about:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/39650930/108591126-5e8c2280-7367-11eb-8f73-e4aaec034612.png">

<img width="465" alt="image" src="https://user-images.githubusercontent.com/39650930/108591160-93987500-7367-11eb-9bca-860ff576b162.png">

I'm not a web developer, but should a responsive theme not adapt to devices with smaller screens as well? I know there are limits of what one can and cannot support, but I think that scaling down the the post title, the date with the circle and the tags for devices with a resolution between 250 and 450px in width should work just fine. If that is not ideal, how about just displaying the post title for these devices?

IIRC `@media (max-width:450px) { css... }` should work to apply the css modifications only for devices with a resolution of lower than 450px in width.

Thanks in advance!

**Comment by somratpro** [comment]
@totoroot 

thanks for letting us know about this issue, we fixed it. you can download the latest version and enjoy it...

**Comment by totoroot** [comment]
Thank you, works great!
