### ISSUE TITLE
How to add images?

### ISSUE THREAD

**Issue by anapaulagomes** [gethugothemes/persian-hugo#13]
Hi! First, thanks for this great theme.

My question is: how can I add images to the posts? I've tried different combinations and had no luck so far:

```
![](images/post/luz/luzes.gif)
![](post/luz/luzes.gif)
![](static/images/post/luz/bike.jpg)
![](images/post/luz/bike.jpg)
![](post/luz/bike.jpg)
```

All images are valid and exist in `static/images/post/luz/` directory.

**Comment by somratpro** [comment]
try `![](../images/post/luz/luzes.gif)` or `![](../..images/post/luz/luzes.gif)` it should work

**Comment by anapaulagomes** [comment]
It worked with `![](../../images/post/luz/luzes.gif)`. Thanks!
