### ISSUE TITLE
Social Media Icons Not Displaying

### ISSUE THREAD

**Issue by gshick** [gethugothemes/persian-hugo#5]
Can the social media icons in the john-doe.MD be included in other places, such as the contact page _index.md?

Are you supposed to be able to set social: true in md files or do you need the full code below?

social:
  - icon : "ti-facebook" # themify icon pack : https://themify.me/themify-icons
    link : "#"
  - icon : "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
    link : "#"
  - icon : "ti-github" # themify icon pack : https://themify.me/themify-icons
    link : "#"

**Comment by developer-evan** [comment]
Hey @gshick 

`John.md` social icons are only for this author's single page. I see the demo and run it on my localhost. icons are rendering correctly. please download the latest code and check it again. thanks

**Comment by gshick** [comment]
Ok, thanks.  That's what I wanted to verify that we couldn't add those to other pages in the MD files.  In case anyone else ever needs this fix, my work around was to add custom HTML to the list.html in the Persian layouts page of the pages I wanted:

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<section class="section pt-1">
  <div class="container" style="text-align: center">
    <div class="row col-lg-5 mx-auto justify-content-center" >
      <div class="form-group col-sm-2">
        <a href="mailto: "." class="fa fa-envelope-o" style="font-size: 3em;"> </a>
      </div>
      <div class="form-group col-sm-2">
        <a href="." class="fa fa-facebook-official" style="font-size: 3em;"> </a>
      </div>
      <div class="form-group col-sm-2">
        <a href="." class="fa fa-linkedin-square" style="font-size: 3em;"> </a>
      </div>
      <div class="form-group col-sm-2">
        <a href="." class="fa fa-instagram" style="font-size: 3em;"> </a>
      </div>
    </div>    
  </div>
</section>
