### ISSUE TITLE
How to use local fonts?

### ISSUE THREAD

**Issue by Skabit** [gethugothemes/persian-hugo#6]
I really appreciate your work. But I'm newbie on Hugo and Sass. I want to use a local font, but I can't achieve to work with any process. Now, I'm using Persian theme with Github.

Firstly, I've used a scss file in the next path `/resources/_gen/assets/scss/scss/` for customize the blog, this file is called `style.scss_f300667da4f5b5f84e1a9e0702b2fdde.content`. It is a weird method, but It is the only file when the changes works. (Please tell me what is the correct file to customize the blog).

Well, to change the fonts I follow the next process:

- Path: `theme/persian/assets/scss/_typography.scss`
- Edit `_typography.scss` file, comment google-font reference and add the next line:
            
      @font-face {
          font-family: "Montserrat";
          src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
          url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
          }
- Create a new folder with the font files: `theme/persian/assets/scss/fonts/`
- Modify `_variables.scss` file for reference to new font: 'Montserrat', and replace any font reference with the new font name.

Then, when I have all this procces nothing happens.

P.S: When I try replicate the internal structure of the theme folder (`theme/persian`) on the root of the repository I think that is possible delete `resources/_gen/...` folder, but when I try it a error message appears, exactly What is the work/fuction of `resources/_gen` folder and its files?

**Comment by developer-evan** [comment]
Hello @Skabit 

Thanks for using our template, you did some mistake. first of all, you need to place the fonts in `static` folder. not in `asstes` folder.  it should be `static/fonts` 

then `src: url("../fonts/OpenSans-Regular-webfont.woff2") format("woff2")`

**Comment by Skabit** [comment]
Wow, I can now use a local font. Thanks for the hint.
