### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by Skabit** [gethugothemes/persian-hugo#8]
Then to modify the `config.toml` the search function doesn't work. I've compared my blog with live [demo](https://demo.themefisher.com/persian-hugo/) of Persian, and I see the next behavior:

1. When type any word on search section the url bar on the explorer looks like that:

       https://example.com/search

2. But when type on live demo page, the URL looks different:

       https://demo.themefisher.com/persian-hugo/search/?s=word

By some weird problem when type on the search section my blog don't complete the query. But if I type `?s=word` on the url bar (https://example.com/search/?s=word) the search function works.

What is the reason of this behavior?

**Comment by somratpro** [comment]
Hello @Skabit 

Did you change the search form action?

**Comment by Skabit** [comment]
Hello @somratpro

Where is the search form action?

**Comment by somratpro** [comment]
In `layouts/partials/footer.html`

**Comment by Skabit** [comment]
In `layouts/partials/footer.html` I have mixing a few lines, I follow the next code taken from the original file (in this repo):

```
{{ "<!-- Search index -->" | safeHTML }}
{{ if .Site.Params.search }}
<script>
  var indexURL = {{"index.json" | absURL}}
</script>
{{ end }}
```

Thanks for the hint
