### ISSUE TITLE
Author page looks weird on Search page

### ISSUE THREAD

**Issue by Skabit** [gethugothemes/persian-hugo#9]
Today I probed the search function and see that when in the results appears the author page, the output looks terrible (look the screenshot). 

Is possible exclude the author page of the search process? or How to fix this behavior? 

![error](https://user-images.githubusercontent.com/71466998/104856324-faaab000-5909-11eb-8af7-7c15b3ef28d9.png)

**Comment by somratpro** [comment]
Hello @Skabit 

This issue has been fixed, please download the latest code and enjoy!

**Comment by Skabit** [comment]
Thanks for your work. Fix it!
